{% set name = "less-learn" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/less-learn-{{ version }}.tar.gz
  sha256: 05dc393981d09113e9e2f089ed391d317d0b02279078b4283e22536bf0810f00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.21.5
    - python >=3.6
    - scikit-learn >=1.0.1

test:
  imports:
    - less
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sibirbil/LESS
  summary: Learning with Subset Stacking
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sibirbil
